<?php
session_start();
require_once '../includes/config.php';

if (is_logged_in()) {
    redirect('../index.php');
    }

    $error = '';

    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
        $username = sanitize($_POST['username']);
            $password = sanitize($_POST['password']);
                
                    $query = "SELECT * FROM users WHERE username = '$username'";
                        $result = $conn->query($query);
                            
                                if ($result->num_rows == 1) {
                                        $user = $result->fetch_assoc();
                                                
                                                        if (password_verify($password, $user['password'])) {
                                                                    $_SESSION['user_id'] = $user['id'];
                                                                                $_SESSION['username'] = $user['username'];
                                                                                            $_SESSION['role'] = $user['role'];
                                                                                                        $_SESSION['masjid_id'] = $user['masjid_id'];
                                                                                                                    
                                                                                                                                if ($user['role'] == 'Admin Pusat') {
                                                                                                                                                redirect('../pages/dashboard_admin.php');
                                                                                                                                                            } elseif ($user['role'] == 'Guru') {
                                                                                                                                                                            redirect('../pages/dashboard_guru.php');
                                                                                                                                                                                        } else {
                                                                                                                                                                                                        redirect('../pages/dashboard_murid.php');
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                        $error = 'Username atau password salah';
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                            $error = 'Username atau password salah';
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                ?>

                                                                                                                                                                                                                                                                <!DOCTYPE html>
                                                                                                                                                                                                                                                                <html lang="en">
                                                                                                                                                                                                                                                                <head>
                                                                                                                                                                                                                                                                    <meta charset="utf-8">
                                                                                                                                                                                                                                                                        <meta name="viewport" content="width=device-width, initial-scale=1">
                                                                                                                                                                                                                                                                            <title>Login - TPQ Masjid</title>
                                                                                                                                                                                                                                                                                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
                                                                                                                                                                                                                                                                                    <link rel="stylesheet" href="../assets/css/all.min.css">
                                                                                                                                                                                                                                                                                        <link rel="stylesheet" href="../assets/css/adminlte.min.css">
                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                        <body class="hold-transition login-page">
                                                                                                                                                                                                                                                                                        <div class="login-box">
                                                                                                                                                                                                                                                                                            <div class="login-logo">
                                                                                                                                                                                                                                                                                                    <a href="../index.php"><b>TPQ</b> Masjid</a>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                    <div class="card-body login-card-body">
                                                                                                                                                                                                                                                                                                                                <p class="login-box-msg">Silakan login untuk memulai sesi</p>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                        <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-danger"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                            <form action="" method="post">
                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="input-group mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" class="form-control" placeholder="Username" name="username" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="input-group-append">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="input-group-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="fas fa-user"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="input-group mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" class="form-control" placeholder="Password" name="password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="input-group-append">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="input-group-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="fas fa-lock"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="col-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="icheck-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" id="remember">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label for="remember">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ingat Saya
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="forgot-password.html">Lupa password?</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="mb-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="register.php" class="text-center">Daftar akun baru</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script src="../assets/js/jquery.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script src="../assets/js/bootstrap.bundle.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script src="../assets/js/adminlte.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </html>